### ISSUE TITLE
丢数据

### ISSUE THREAD

**Issue by andyyinggh** [aliyun/aliyun-log-log4j2-appender#12]
看了源码，如果日志发送失败，只是通过回调函数打印了失败的日志。这样会丢数据的。
public void onCompletion(PutLogsResponse putLogsResponse, LogException e) {
        if (e != null) {
            logger.error("Failed to putLogs. project=" + project + " logstore=" + logstore +
                    " topic=" + topic + " source=" + source + " logItems=" + logItems, e);
        }
    }

**Comment by brucewu-fly** [comment]
你好，内部会根据配置文件中指定的 retryTimes 进行重试，重试超过这个次数后才会回调这个接口。
如果您不希望数据丢失，可适当提高这个值。
