### ISSUE TITLE
Log4J2 Appender是否可以工作？

### ISSUE THREAD

**Issue by linkmancheng** [aliyun/aliyun-log-log4j2-appender#8]
请问Log4J2 appender 是否可以工作？ 是否可以将日志打到Log Hub中。 应当如何配置？ 谢谢。

**Comment by brucewu-fly** [comment]
@linkmancheng ，您可以参考 https://github.com/aliyun/aliyun-log-log4j2-appender/blob/master/README_CN.md 这篇文档中的 **配置步骤** 部分进行使用。
如果您在使用过程中遇到了问题，可以先参考 **错误诊断** 部分进行问题排查。
文档的 **使用实例** 部分有sample程序。
